<!--
  Copyright (C) 2025 Rostislav Suleimanov

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<?php
?>
<div class="product-name">
    <?php echo $block->escapeHtml($_product->getName()); // Noncompliant {{Short echo tag syntax must be used; expected "<?=" but found "<?php echo"}} ?>
</div>

<span class="price">
    <?php echo $block->formatPrice($_product->getPrice()); // Noncompliant {{Short echo tag syntax must be used; expected "<?=" but found "<?php echo"}} ?>
</span>

<div class="description">
    <?php echo $block->escapeHtml($_product->getDescription()); // Noncompliant {{Short echo tag syntax must be used; expected "<?=" but found "<?php echo"}} ?>
</div>

<div class="product-name">
    <?= $block->escapeHtml($_product->getName()) // Compliant ?>
</div>

<span class="price">
    <?= $block->formatPrice($_product->getPrice()) // Compliant ?>
</span>

<div class="description">
    <?= $block->escapeHtml($_product->getDescription()) // Compliant ?>
</div>