<!--
  Copyright (C) 2025 Rostislav Suleimanov

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<?php
$helper = $block->getHelper(); // Noncompliant {{The use of helpers in templates is discouraged. Use ViewModel instead.}}
$_helper = $block->getHelper(); // Noncompliant {{The use of helpers in templates is discouraged. Use ViewModel instead.}}
$someData = $this->getData(); // Noncompliant {{The use of $this in templates is deprecated. Use $block instead.}}
?>

<div>
    <?= $this->getHtmlData(); // Noncompliant {{The use of $this in templates is deprecated. Use $block instead.}} ?>
</div>