<!--
  Copyright (C) 2025 Rostislav Suleimanov

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<div>
    <?= __('Text to translate') // Noncompliant {{Unescaped output detected.}} ?>
    <?php echo $customer->getName() // Noncompliant {{Unescaped output detected.}} ?>

    <?= $escaper->escapeHtml(__('Text to translate')) // Compliant ?>
    <?= $block->getChildBlock('test')->toHtml() // Compliant ?>
    <?php echo $escaper->escapeHtml($customer->getName()) // Compliant ?>
    <?php echo 1 // Compliant?>
    <?= /* @escapeNotVerified */ __('Test') // Compliant?>
    <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->testMethod(
                $block->getData(),
                $block->getAdditionalData(),
                'description'
            ) ?>
    <?= $test
        ? '123'
        : $block->getSomeInfo() // Noncompliant {{Unescaped output detected.}}
    ?>
</div>