<div>
    <?= __('Text to translate') // Noncompliant {{Unescaped output detected.}} ?>
    <?php echo $customer->getName() // Noncompliant {{Unescaped output detected.}} ?>

    <?= $escaper->escapeHtml(__('Text to translate')) // Compliant ?>
    <?= $block->getChildBlock('test')->toHtml() // Compliant ?>
    <?php echo $escaper->escapeHtml($customer->getName()) // Compliant ?>
    <?php echo 1 // Compliant?>
    <?= /* @escapeNotVerified */ __('Test') // Compliant?>
    <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->testMethod(
                $block->getData(),
                $block->getAdditionalData(),
                'description'
            ) ?>
    <?= $test
        ? '123'
        : $block->getSomeInfo() // Noncompliant {{Unescaped output detected.}}
    ?>
</div>